
export const CHILD_CREATE_ITEM = 'tam/CHILD_CREATE_ITEM';
export const CHILD_CREATE_ITEM_SUCCESS = 'tam/CHILD_CREATE_ITEM_SUCCESS';
export const CHILD_CREATE_ITEM_FAILED = 'tam/CHILD_CREATE_ITEM_FAILED';

export const CHILD_CREATE_INFO = 'tam/CHILD_CREATE_INFO';
export const CHILD_CREATE_INFO_SUCCESS = 'tam/CHILD_CREATE_INFO_SUCCESS';
export const CHILD_CREATE_INFO_FAILED = 'tam/CHILD_CREATE_INFO_FAILED';

export const CHILD_CREATE_ADMIN = 'tam/CHILD_CREATE_ADMIN';
export const CHILD_CREATE_ADMIN_SUCCESS = 'tam/CHILD_CREATE_ADMIN_SUCCESS';
export const CHILD_CREATE_ADMIN_FAILED = 'tam/CHILD_CREATE_ADMIN_FAILED';

export const CHILD_LIST_ADMINS = 'tam/CHILD_LIST_ADMINS';
export const CHILD_LIST_ADMINS_SUCCESS = 'tam/CHILD_LIST_ADMINS_SUCCESS';
export const CHILD_LIST_ADMINS_FAILED = 'tam/CHILD_LIST_ADMINS_FAILED';

