export const COMMENT_CREATE_ITEM = 'tam/COMMENT_CREATE_ITEM'
export const COMMENT_CREATE_ITEM_SUCCESS = 'tam/COMMENT_CREATE_ITEM_SUCCESS'
export const COMMENT_CREATE_ITEM_FAILED = 'tam/COMMENT_CREATE_ITEM_FAILED'

export const COMMENT_FETCH_LIST = 'tam/COMMENT_FETCH_LIST'
export const COMMENT_FETCH_LIST_SUCCESS = 'tam/COMMENT_FETCH_LIST_SUCCESS'
export const COMMENT_FETCH_LIST_FAILED = 'tam/COMMENT_FETCH_LIST_FAILED'

export const COMMENT_UPDATE_ITEM = 'tam/COMMENT_UPDATE_ITEM'
export const COMMENT_UPDATE_ITEM_SUCCESS = 'tam/COMMENT_UPDATE_ITEM_SUCCESS'
export const COMMENT_UPDATE_ITEM_FAILED = 'tam/COMMENT_UPDATE_ITEM_FAILED'

export const COMMENT_REMOVE_ITEM = 'tam/COMMENT_REMOVE_ITEM'
export const COMMENT_REMOVE_ITEM_SUCCESS = 'tam/COMMENT_REMOVE_ITEM_SUCCESS'
export const COMMENT_REMOVE_ITEM_FAILED = 'tam/COMMENT_REMOVE_ITEM_FAILED'