export const IMAGE_CREATE_ITEM = 'tam/IMAGE_CREATE_ITEM'
export const IMAGE_CREATE_ITEM_SUCCESS = 'tam/IMAGE_CREATE_ITEM_SUCCESS'
export const IMAGE_CREATE_ITEM_FAILED = 'tam/IMAGE_CREATE_ITEM_FAILED'

export const IMAGE_UPDATE_ITEM = 'tam/IMAGE_UPDATE_ITEM'
export const IMAGE_UPDATE_ITEM_SUCCESS = 'tam/IMAGE_UPDATE_ITEM_SUCCESS'
export const IMAGE_UPDATE_ITEM_FAILED = 'tam/IMAGE_UPDATE_ITEM_FAILED'
 
export const IMAGE_REMOVE_ITEM = 'tam/IMAGE_REMOVE_ITEM'
export const IMAGE_REMOVE_ITEM_SUCCESS = 'tam/IMAGE_REMOVE_ITEM_SUCCESS'
export const IMAGE_REMOVE_ITEM_FAILED = 'tam/IMAGE_REMOVE_ITEM_FAILED'
 