export const POST_FETCH_LIST = 'tam/POST_FETCH_LIST';
export const POST_FETCH_LIST_SUCCESS = 'tam/POST_FETCH_LIST_SUCCESS';
export const POST_FETCH_LIST_FAILED = 'tam/POST_FETCH_LIST_FAILED'; 

export const POST_FETCH_DETAIL = 'tam/POST_FETCH_DETAIL';
export const POST_FETCH_DETAIL_SUCCESS = 'tam/POST_FETCH_DETAIL_SUCCESS';
export const POST_FETCH_DETAIL_FAILED = 'tam/POST_FETCH_DETAIL_FAILED'; 

export const POST_CREATE_ITEM = 'tam/POST_CREATE_ITEM'; 
export const POST_CREATE_ITEM_SUCCESS = 'tam/POST_CREATE_ITEM_SUCCESS'; 
export const POST_CREATE_ITEM_FAILED = 'tam/POST_CREATE_ITEM_FAILED'; 

export const POST_CREATE_ITEM_PART = 'tam/POST_CREATE_ITEM_PART'; 
export const POST_CREATE_ITEM_PART_SUCCESS = 'tam/POST_CREATE_ITEM_PART_SUCCESS'; 
export const POST_CREATE_ITEM_PART_FAILED = 'tam/POST_CREATE_ITEM_PART_FAILED'; 

export const POST_UPDATE_ITEM = 'tam/POST_UPDATE_ITEM'; 
export const POST_UPDATE_ITEM_SUCCESS = 'tam/POST_UPDATE_ITEM_SUCCESS'; 
export const POST_UPDATE_ITEM_FAILED = 'tam/POST_UPDATE_ITEM_FAILED'; 

export const POST_REMOVE_ITEM = 'tam/POST_REMOVE_ITEM'; 
export const POST_REMOVE_ITEM_SUCCESS = 'tam/POST_REMOVE_ITEM_SUCCESS'; 
export const POST_REMOVE_ITEM_FAILED = 'tam/POST_REMOVE_ITEM_FAILED'; 
