export const USER_LOGIN = 'tam/USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'tam/USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'tam/USER_LOGIN_FAILED';

export const VERIFY_USER_TOKEN = 'tam/VERIFY_USER_TOKEN';
export const VERIFY_USER_TOKEN_SUCCESS = 'tam/VERIFY_USER_TOKEN_SUCCESS';
export const VERIFY_USER_TOKEN_FAILED = 'tam/VERIFY_USER_TOKEN_FAILED';

export const USER_REGISTER = 'tam/USER_REGISTER';
export const USER_REGISTER_SUCCESS = 'tam/USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILED = 'tam/USER_REGISTER_FAILED';

export const REQUEST_RECOVERY = 'tam/REQUEST_RECOVERY';
export const REQUEST_RECOVERY_SUCCESS = 'tam/REQUEST_RECOVERY_SUCCESS';
export const REQUEST_RECOVERY_FAILED = 'tam/REQUEST_RECOVERY_FAILED';

export const USER_FETCH_DETAIL = 'tam/USER_FETCH_DETAIL';
export const USER_FETCH_DETAIL_SUCCESS = 'tam/USER_FETCH_DETAIL_SUCCESS';
export const USER_FETCH_DETAIL_FAILED = 'tam/USER_FETCH_DETAIL_FAILED';

export const USER_EDIT_ITEM = 'tam/USER_EDIT_ITEM';
export const USER_EDIT_ITEM_SUCCESS = 'tam/USER_EDIT_ITEM_SUCCESS';
export const USER_EDIT_ITEM_FAILED = 'tam/USER_EDIT_ITEM_FAILED';


